export const data = [
	{
		id: 1,
		name: 'E-Commerce App',
		image: '/ecommerce1.png',
		stack:
			'Next.JS | MongoDB | Context API | Next-Auth | JS-Cookie | Bcrypt | React Hooks | TailwindCSS',
		description: [
			'Built with Next.JS',
			'MongoDB used as the Database',
			'Context API was complemented with JS-Cookie for state mangement',
			'Credential Authentication built using Next-Auth',
			'Paypal API was integrated as the payment service',
			'Bcrypt for password hashing',
			'TailwindCSS for styling',
			'React Toastify to enhance user experience',
		],
		url: 'https://greenshopping.vercel.app',
		github: 'https://github.com/numofran6/Green-Shop',
	},
	{
		id: 2,
		name: 'Realtime Chat App',
		image: '/chat1.png',
		stack:
			'React | Firebase | SASS | Styled Components | React Hooks | React Router DOM',
		description: [
			'React.JS to build single-page application',
			'Firebase Data-store was used for Database',
			'Authentication functionality handled by Firebase',
			'SASS and Styled Components for styling UI',
			'React Router DOM to handle routing and protected pages',
			'Real-time Chatting possible even without a web socket because of amazing Firebase functionalities',
		],
		url: 'https://kasachat.vercel.app/',
		github: 'https://github.com/numofran6/kasa',
	},
	{
		id: 3,
		name: 'Church App',
		image: '/church.png',
		stack: 'Next.js | TailwindCSS | Styled Components | React Hooks',
		description: [
			'Next.js to build single-page application',
			'TailwindCSS and Styled Components for styling UI',
		],
		url: 'https://glorioushill.vercel.app/',
		github: 'https://github.com/numofran6/church-website',
	},
	{
		id: 4,
		name: 'Cisco Virtual Experience Program',
		image: '/sextant.png',
		stack: 'React.js | Node.js | Web Sockets | Styled Components | React Hooks',
		description: [
			'Developed a network dashboard called Sextant',
			'Used React as the frontend framework',
			'Prepared extensible components for data points that are likely to change overtime',
			'Worked with the ipify-API to collect and display a user’s public ipv4 and ipv6 addresses',
			'Established a websocket connection with a node server to determine how long data packets take to traverse the network',
		],
		url: 'https://numofran6.github.io/cisco-starter-repo/',
		github: 'https://github.com/numofran6/cisco-starter-repo',
	},
];
