export const data = [
	{
		id: 1,
		name: 'Green Shop',
		image: '/ecommerce1.png',
		stack:
			'Next.JS | MongoDB | Context API | Next-Auth | JS-Cookie | Bcrypt | React Hooks | TailwindCSS',
		description: [
			'Accomplished the development of this web application using Next.JS',
			'MongoDB was used as the Database to store user information',
			'Enhanced user interface and experience using Tailwind CSS and React Toastify',
			'Context API was complemented with JS-Cookie for state mangement',
			'Developed Credential Authentication feature using Next-Auth',
			'Integrated the Paypal API as the payment service',
			'Bcrypt for password hashing',
		],
		url: 'https://greenshopping.vercel.app',
		github: 'https://github.com/numofran6/Green-Shop',
	},
	{
		id: 2,
		name: 'Kasa Chat App',
		image: '/chat1.png',
		stack:
			'React | Firebase | SASS | Styled Components | React Hooks | React Router DOM',
		description: [
			'Built a single-page application using React.JS',
			'Firebase Datastore was used for storing user information',
			'Built the Authentication Login/Register feature using Firebase Authentication',
			'Designed the user interface and experience using SASS and Styled Components',
			'Handled routing and protected routes using React Router DOM',
		],
		url: 'https://kasachat.vercel.app/',
		github: 'https://github.com/numofran6/kasa',
	},
	{
		id: 3,
		name: 'Church Blog',
		image: '/church.png',
		stack: 'Next.js | TailwindCSS | Styled Components | React Hooks',
		description: [
			'Developed and designed front end architecture',
			'Implemented highly responsive user interface components using React concepts and JavaScript workflows',
			'Handled optimization, maintenance, and upgrade',
			'Designed responsiveness across various media viewports',
			'Handled troubleshooting interface and debugging application codes',
		],
		url: 'https://glorioushill.vercel.app/',
		github: 'https://github.com/numofran6/church-website',
	},
	{
		id: 4,
		name: 'Cisco Virtual Internship',
		image: '/sextant.png',
		stack: 'React.js | Node.js | Web Sockets | Styled Components | React Hooks',
		description: [
			'Developed a network dashboard called Sextant',
			'Used React as the frontend framework',
			'Prepared extensible components for data points that are likely to change overtime',
			'Worked with the ipify-API to collect and display a user’s public ipv4 and ipv6 addresses',
			'Established a websocket connection with a node server to determine how long data packets take to traverse the network',
		],
		url: 'https://numofran6.github.io/cisco-starter-repo/',
		github: 'https://github.com/numofran6/cisco-starter-repo',
	},
];
